name: Deploy to Render

on:
  push:
    branches:
      - master  # or 'main' if that's your default branch
  workflow_dispatch:  # Allows manual trigger

jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url" 